import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("find", "routes/find.tsx"),
  route("spaces", "routes/spaces.tsx"),
  route("s/:slug", "routes/survey.tsx"),
  route("r/:slug", "routes/public-report.tsx"),
  route("apply/:slug", "routes/apply.tsx"),
  route("result/:token", "routes/result.tsx"),
  route("media/space/:slug/cover", "routes/space-cover.tsx"),
  route("owner", "routes/owner-login.tsx"),
  route("owner/verify", "routes/owner-verify.tsx"),
  route("owner/welcome", "routes/owner-welcome.tsx"),
  route("owner/logout", "routes/owner-logout.tsx"),
  route("owner/spaces", "routes/owner-spaces.tsx"),
  route("owner/spaces/new", "routes/owner-space-new.tsx"),
  route("owner/spaces/:id/cover", "routes/owner-space-cover.tsx"),
  route("owner/spaces/:id/photos", "routes/owner-space-photos.tsx"),
  route("owner/spaces/:id/edit", "routes/owner-space-edit.tsx"),
  route("owner/spaces/:id/candidates", "routes/owner-candidates.tsx"),
  route("admin/login", "routes/admin-login.tsx"),
  route("admin/logout", "routes/admin-logout.tsx"),
  route("admin/files/*", "routes/admin-file.tsx"),
  layout("routes/admin-layout.tsx", [
    route("admin", "routes/admin-index.tsx"),
    route("admin/spaces", "routes/admin-spaces.tsx"),
    route("admin/applications", "routes/admin-applications.tsx"),
    route("admin/owners", "routes/admin-owners.tsx"),
    route("admin/spaces/new", "routes/admin-space-new.tsx"),
    route("admin/spaces/:id", "routes/admin-space.tsx"),
    route("admin/applications/:id", "routes/admin-application.tsx"),
  ]),
] satisfies RouteConfig;
